2022/03/31 23:38:19 [error] 64#64: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: example.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2022/03/31 23:38:35 [error] 63#63: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: example.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2022/03/31 23:38:54 [error] 64#64: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: example.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
2022/03/31 23:38:54 [error] 64#64: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: example.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
2022/03/31 23:38:55 [error] 64#64: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: example.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
2022/03/31 23:39:35 [error] 68#68: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2022/03/31 23:41:41 [error] 73#73: *55 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.0.0.2, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://10.0.1.226:9000", host: "127.0.0.1"
